crud/crud/urls.py
from django.contrib import admin
from django.urls import path
from gridApp.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index),
    path('addnew', addnew),
    path('edit/<int:id>', edit),
    path('update/<int:id>', update),
    path('delete/<int:id>', delete),
]

crud/gridApp/models.py
from django.db import models

# Create your models here.
class Employes(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField()
    contact = models.CharField(max_length=10)

    class Meta:
        db_table = 'Сотрудники'

crud/gridApp/forms.py
from django import forms
from .models import *

class EmployerForm(forms.ModelForm):
    class Meta:
        model = Employes
        fields = ['name', 'contact', 'email']
        widgets = {
            'name' : forms.TextInput(
                attrs={'class': 'form-control'}
            ),
            'contact': forms.TextInput(
                attrs={'class': 'form-control',
                       'placeholder': 'Сюда номер телефона'}
            ),
            'email': forms.EmailInput(
                attrs={'class': 'form-control'}
            )
        }

crud/gridApp/views.py
from django.shortcuts import render, redirect
from gridApp.forms import EmployerForm
from gridApp.models import Employes

# Create your views here.

def addnew(request):
    if request.method == "POST":
        form = EmployerForm(request.POST)
        if form.is_valid():
            try:
                form.save()
                return redirect('/')
            except:
                pass
    else:
        form = EmployerForm()
    return render(request,'gridApp/index.html',{'form':form})
def index(request):
    employees = Employes.objects.all()
    return render(request,"gridApp/show.html",{'employees':employees})
def edit(request, id):
    employee = Employes.objects.get(id=id)
    return render(request,'gridApp/edit.html', {'employee':employee})
def update(request, id):
    employee = Employes.objects.get(id=id)
    form = EmployerForm(request.POST, instance = employee)
    if form.is_valid():
        form.save()
        return redirect("/")
    return render(request, 'gridApp/edit.html', {'employee': employee})
def delete(request, id):
    employee = Employes.objects.get(id=id)
    employee.delete()
    return redirect("/")

crud/gridApp/templates/gridApp/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{%block title%}{%endblock%}</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"></script>
    <script src="http://code.jquery.com/jquery-1.11.1.min.js"></script>
    <script
            src="https://cdn.datatables.net/1.11.3/css/dataTables.bootstrap5.min.css"></script>
    <script src="https://cdn.datatables.net/1.11.3/js/jquery.dataTables.min.js"></script>
</head>
<body>
<div class="container">
    <div class="row">
        {% block content %}
        {% endblock %}
    </div>
</div>




<script>
 $(document).ready(function() {
     $('#bootstrapdatatable').DataTable({
       "aLengthMenu": [[3, 5, 10, 25, -1], [3, 5, 10, 25, "All"]],
         "iDisplayLength": 3
        }
     );
 } );
 </script>
</body>
</html>

crud/gridApp/templates/gridApp/edit.html
{% extends "gridApp/base.html" %}

{% block title %}Add New Employee Records{% endblock title %}

{% block content %}
<div class="col-md-12">
    <h4>Django CRUD</h4>
 <form method="POST" class="post-form" action="/update/{{employee.id}}">
   {% csrf_token %}
     <div class="container">
         <br>
         <div class="form-group row">
            <label class="col-sm-1 col-form-label"></label>
                <div class="col-sm-4">
                    <h3>Enter Detail</h3>
                </div>
         </div>
         <div class="form-group row">
             <label class="col-sm-2 col-form-label">Id сотрудника:</label>
             <div class="col-sm-4">
                <input type="text" class="form-control" name="id" id="id_id" required maxlength="20" value="{{ employee.id }}"/>
             </div>
         </div>
         <div class="form-group row">
             <label class="col-sm-2 col-form-label">Имя сотрудника:</label>
             <div class="col-sm-4">
                 <input type="text" class="form-control" name="name" id="id_name" required maxlength="100" value="{{ employee.name }}" />
             </div>
         </div>
         <div class="form-group row">
             <label class="col-sm-2 col-form-label">Емайл:</label>
             <div class="col-sm-4">
                 <input type="email" class="form-control" name="email" id="id_email" required maxlength="254" value="{{ employee.email }}" />
             </div>
         </div>
         <div class="form-group row">
             <label class="col-sm-2 col-form-label">Контакты:</label>
                <div class="col-sm-4">
                    <input type="text" class="form-control" name="contact" id="id_contact" required maxlength="15" value="{{ employee.contact }}" />
                </div>
         </div>
         <div class="form-group row">
             <label class="col-sm-1 col-form-label"></label>
             <div class="col-sm-4">
                 <button type="submit" class="btn btn-success btn-lg">Добавить</button>
             </div>
         </div>
     </div>
 </form>
{% endblock content %}

crud/gridApp/templates/gridApp/index.html
{% extends 'gridApp/base.html' %}

{% block content %}
<div class="col-md-12">
    <h4> Django CRUD </h4>
    <form method="POST" class="post-form" action="/addnew">
        {% csrf_token %}
        <div class="container">
            <br>
            <div class="form-group row">
                <label class="col-sm-1 col-form-label">
                    <div class="col-sm-4">
                        <h3> Enter Detail </h3>
                    </div>
                </label>
            </div>
        </div>

        <div class="form-group row">
        <label class="col-sm-2 col-form-label">Имя сотрудника</label>
        <div class="col-sm-4">
            {{ fuck.name }}
        </div>
    </div>

    <div class="form-group row">
        <label class="col-sm-2 col-form-label">Емайл</label>
        <div class="col-sm-4">
            {{ fuck.email }}
        </div>
    </div>

    <div class="form-group row">
        <label class="col-sm-2 col-form-label">Контакты</label>
        <div class="col-sm-4">
            {{ fuck.contact }}
        </div>
    </div>

    <div class="form-group row">
        <label class="col-sm-2 col-form-label"></label>
        <div class="col-sm-4">
            <button type="submit"
                    class="btn btn-primary">Добавить</button>
        </div>
    </div>



    </form>
</div>
{% endblock %}

crud/gridApp/templates/gridApp/show.html
{% extends "gridApp/base.html" %}

{% block title %}Employee Records{% endblock title %}

{% block content %}
 <div class="col-md-12">
        <h4>Django CRUD (Create Read Update Delete) Example - Bootstrap Datatable GRID</h4> <span><a href="/addnew" class="btn btn-primary">Add New Record</a></span>
        <div class="table-responsive">
  <table id="bootstrapdatatable" class="table table-striped table-bordered" width="100%">
            <thead>
                <th><input type="checkbox" id="checkall" /></th>
                <th>ID</th>
                <th>Employee Name</th>
                <th>Employee Email</th>
                <th>Employee Contact</th>
                <th>Edit</th>
                <th>Delete</th>
             </thead>
   <tbody>
   {% for employee in employees %}
    <tr>
     <td><input type="checkbox" class="checkthis" /></td>
     <td>{{ employee.id }}</td>
     <td>{{ employee.name }}</td>
     <td>{{ employee.email }}</td>
     <td>{{ employee.contact }}</td>
     <td><p data-placement="top" data-toggle="tooltip" title="Edit"><a href="/edit/{{ employee.id }}" class="btn btn-primary btn-xs" data-title="Edit" data-toggle="modal" data-target="#edit" ><span class="glyphicon glyphicon-pencil"></span></a></p></td>
     <td><p data-placement="top" data-toggle="tooltip" title="Delete"><a href="/delete/{{ employee.id }}" class="btn btn-danger btn-xs" data-title="Delete" data-toggle="modal" data-target="#delete" ><span class="glyphicon glyphicon-trash"></span></a></p></td>
    </tr>
   {% endfor %}
   </tbody>

  </table>
        </div>
    </div>
{% endblock content %}